timeout 1
menu title Boot the OS
default Linux

label Linux
	kernel /vmlinuz
	fdt /
	initrd /initrd.img
	append earlycon console=tty0 console=ttyMSM0,115200 root=UUID=894a654a-fd79-464b-99ae-d83b4cd35382 rw loglevel=7
